version: '3'

services:
  metagpt:
    image: metagpt/metagpt:latest
    container_name: metagpt
    restart: unless-stopped
    volumes:
      - ./workspace:/app/workspace
      - ./.metagpt:/root/.metagpt
    environment:
      - http_proxy=${http_proxy}
      - https_proxy=${https_proxy}
      - OPENAI_API_KEY=${OPENAI_API_KEY}
    ports:
      - "8000:8000"
    command: /bin/bash -c "sleep infinity"

  # Optional: Include Ollama for local LLM support
  ollama:
    image: ollama/ollama:latest
    container_name: ollama
    restart: unless-stopped
    volumes:
      - ./ollama:/root/.ollama
    ports:
      - "11434:11434"
    deploy:
      resources:
        reservations:
          devices:
            - driver: nvidia
              count: 1
              capabilities: [gpu]